### ISSUE TITLE
APIリファレンスの誤り

### ISSUE THREAD

**Issue by popkechupki** [itsu-dev/NukkitFormAPI#1]
APIリファレンスには以下をインポート
`import itsu.mcbe.form.event.NukkitFormAPI;`
とありますが、このクラスは存在していないのではないでしょうか。

**Comment by itsu-dev** [comment]
ご指摘ありがとうございます。また遅くなって申し訳ありません。
itsu.mcbe.form.core.NukkitFormAPIの誤りでした。
